# Just sends back whatever is submitted to stdin
name: An example of pipeline which reads a file and prints contents line by line to standard output
stages:
- name: File Source
  handler: file
  config:
    path: examples/input_files/simple_lines.txt
- name: Stdout Destination
  handler: stdio
  config:
    output_format: "A line from file '%H[file_name]': %P"
